### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by milooy** [milooy/noote#2]
## TODO
- [x] Create react App
- [x] Apply redux
- [x] Apply markdown Editor
- [x] Make axiosMock Module
- [x] Make view (not using state, just use props)
- [x] Make it runnable
- [x] Design, CSS
- [x] Apply test(jest, enzyme)
- [x] Increase accessibility (e.g. meta tag, share image, favicon, right tag name)
- [x] Auto save with debounce
- [x] Hover animation
- [x] Documentation

## FUTURE
- [x] Release with Firebase
- [ ] Store data in localstorage/firebase (notes, filtering state...)
- [ ] Apply [duck pattern](https://github.com/JisuPark/ducks-modular-redux)
- [ ] Auto search with debounce
- [ ] Improve component test
- [ ] Integration test

**Comment by milooy** [comment]
| Method | URI                  | Action name         | Response                                                                                              |
|--------|----------------------|---------------------|-------------------------------------------------------------------------------------------------------|
| GET    | /api/note/           | fetchNoteList       | [{ id: 1, title: "string", date: "date", notebookId: 1, notebookTitle: "string", contents: "string"}] |
| GET    | /api/notebook/       | fetchNotebookList   | [{ id: 1, title: "string", desc: "string", noteIdList: [], color: "string" }]                         |
| GET    | /api/notebook/${id}/ | fetchNotebookDetail | { id: 1, title: "string", desc: "string", noteIdList: [], color: "string" }                           |
| POST   | /api/note/${id}/     | postNote            | "Note no.${id} successfully saved"                                                                    |
| DELETE | /api/note/${id}/     | deleteNote          | "Note no.${id} successfully deleted"                                                                  |
| PUT    | /api/note/${id}/     | moveNote            | "Note was successfully moved"                                                                         |
